server:
  port: 9000

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant?serverTimezone=UTC&characterEncoding=UTF8
    username: restaurantuser
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    consumer:
      group-id: kafka-consumer-group
      bootstrap-servers: localhost:9092

kafka:
  topics: ORDER-TOPIC

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    register-with-eureka: true
    server-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}